### ISSUE TITLE
Does not show up after install

### ISSUE THREAD

**Issue by albzn540** [Garulf/HA-Commander#1]
First of all, great plugin! (if it could be installed that is)

After installation, nothing shows up. I've changed the variables one's supposed to change.

The plugins show up in the directory you said it would show up: C:\Users\albin\AppData\Roaming\Wox\Plugins

But all other plugins are located in AppData/local and not AppData/roaming, C:\Users\albin\AppData\Local\Wox\app-1.3.524\Plugins

And as you can see from the directory path I have wox version 1.3.524.

My home assistant is running via duckdns and have ssl encryption activated, do you think that could be the issue?

**Comment by albzn540** [comment]
It does not I'm afraid. Is your plugin working for you right now?'
In that case, what version are you running?
Also, is your HA behind a secure SSL connection? Do you have duckdns or do you only control HA from within your network?

Also, is there something I could have missed while installing the plugin?

**Comment by albzn540** [comment]
Solved the issue, I was running python 3.7 and that did not comply well with urllib2.
Also, I solved another issue, in get_attributes() I often got this error:
```
UnboundLocalError: local variable 'joined_attributes' referenced before assignment
```

So I declared `joined_attributes` above the for-loop and the error disappeared and I was able to issue requests to my HA-server

**Comment by Garulf** [comment]
Glad you were able to get it working! 

And sorry you had to deal with my horrible spaghetti code. This was my very first python application.

**Comment by albzn540** [comment]
No problem, amazing work for a first-time python application!

**Comment by kmgalanakis** [comment]
@albzn540 how did you manage to solve this?

**Comment by albzn540** [comment]
@kmgalanakis I did not do much. The commented briefly what changes I made in an earlier comment: https://github.com/Garulf/HA-Commander/issues/1#issuecomment-452060740

The major issue was that I was running another python version. This application should run with python 2.7.
