### ISSUE TITLE
Toggling light not working

### ISSUE THREAD

**Issue by Ombrelin** [Garulf/HA-Commander#33]
When I search my lights they show up, but when I press enter to toggle the light, nothing happens

**Comment by Garulf** [comment]
Hello @Ombrelin! Thanks for bring your issue to my attention. 

Could you please provide the plugin's log located in the plugins root directory?
You should be able to access this directory by going to the following path in Explorer:
```
 %AppData%\FlowLauncher\Plugins
 ```
and navigating to the `HA-Commander` plugin folder from there.

The file you're looking for is named `plugin.log` or `ha-commander.log`

I also have a few questions regarding your issue:

1. Have you tried activating this light using the context menu? (You can reach this menu by selecting the light and pressing <kbd>Shift</kbd>+<kbd>Enter</kbd>
2. Does this happen with other entities or just this one light?

**Comment by Ombrelin** [comment]
Hello @Garulf,
after retrying this morning to reproduce the issue, everything works as expected.
I still went to the log to see whether my failed attempts of yesterday would have produced something helpful, but the log file is empty. In addition, I tried on my other PC and it worked flawlessly on the first try.
Difficult to know what happened, but all that matters is that it works now.
Thank you for your caring answer and my apologies for bothering you with that.

P.S : I have the feeling that your plugin will save me a lot of time when interacting with my HA entities !
