### ISSUE TITLE
Windows 11 HA does not react nor log anything to plugin.log

### ISSUE THREAD

**Issue by manuel-rw** [Garulf/HA-Commander#35]
Hello,
this is a bit awkward.
I am trying to connect my Home Assistant instance to FlowLauncher using your plugin.
When I enter the address and secret, I hit the key combination to bring up the launcher and type "ha" and wait.
It loads for a while, but then ultimately fails.
My first step was, to enter the plugin directory and look out for any errors or hints in the log - but there are none!
The file is 0KB in size;
![image](https://user-images.githubusercontent.com/30572287/198100216-01ce968b-1efc-4970-861e-642dcc412a09.png)

This seems to not be a device related issue, because I had the same log problem on my other AMD based machine.

I would love to provide more information, but there sadly isn't any obvious.
What steps could I take to debug further?

**Comment by Garulf** [comment]
Hello @manuel-rw, thanks for bringing the issue to my attention.

It's hard to say whats going on without much to go on. Are you comfortable trying to run the plugin in your console to see if it outputs an error there?

If so please follow the directions below:

1. Open a console in the plugins directory (usually `%APPDATA%\Flow LAuncher\Plugins\HA-Commander`
2. type `python ./main.py` (this assumes you have Python installed and in your PATH)

This will run the plugin in your console and hopefully either output a very large JSON string or produce an error message trace.

**Comment by manuel-rw** [comment]
Yes, that's no problem for me to do.
I'll get back to you asap when I get some time to do this.

**Comment by manuel-rw** [comment]
```bash
python .\main.py
{"result": [{"Title": "Could not connect to Home Assistant!", "SubTitle": "Please check your settings or network and try again.", "IcoPath": "C:\\Users\\REDACTED\\AppData\\Roaming\\FlowLauncher\\Plugins\\HA-Commander-4.0.0\\icons\\home-assistant.png", "ContextData": null, "Score": 0, "JsonRPCAction": {}, "AutoCompleteText": "ha Could not connect to Home Assistant!"}]}
```

**Comment by manuel-rw** [comment]
The URL, entered in the plugin settings, loads fine in any browser.
Could this be a networking / access issue?
I'm Using Nginx Proxy Manager as reverse proxy for my domain, HASS runs on a subdomain secured with Let's Encyrpt and Cloudflare

**Comment by Garulf** [comment]
> The URL, entered in the plugin settings, loads fine in any browser.
> 
> Could this be a networking / access issue?
> 
> I'm Using Nginx Proxy Manager as reverse proxy for my domain, HASS runs on a subdomain secured with Let's Encyrpt and Cloudflare

Interesting.... I'm running the same setup without cloudflare. You you tried turning off very verification (for testing only)?

**Comment by manuel-rw** [comment]
I think that I tried to connect via the local address (http, no certificates, no proxy) and it didn't work either, but I can check again when I'm back from work.

**Comment by manuel-rw** [comment]
Ok so I'm back with some results.
I tried to connect using the local IP, and it just worked fine.
Next, I tried to disable the Proxy in Cloudflare for the HASS domain, and changed the plugin address to the domain - and it worked.
Then, I re-enabled the Proxy and it still works - I have no idea what's different compared to before!

Sorry for bothering you with this, I really don't know what has changed or why it's working all of a sudden.
We can close this Issue. Thank you for your assistance :)

**Comment by Garulf** [comment]
> Ok so I'm back with some results. I tried to connect using the local IP, and it just worked fine. Next, I tried to disable the Proxy in Cloudflare for the HASS domain, and changed the plugin address to the domain - and it worked. Then, I re-enabled the Proxy and it still works - I have no idea what's different compared to before!

Glad to hear you got it working!

> 
> Sorry for bothering you with this, I really don't know what has changed or why it's working all of a sudden. We can close this Issue. Thank you for your assistance :)

No worries I don't mind helping with issues at all.

> 
> PS: Scenes aren't working for me. Is this intended behavior or not?

It seems I forgot to add support as I hardly use them. I added support with: https://github.com/Garulf/HA-Commander/pull/36

**Comment by manuel-rw** [comment]
Amazing! Thank you. I'll close this now, since my issue has been resolved. Thank you for making this awesome plugin :D
