### ISSUE TITLE
I don't understand how to recover my token

### ISSUE THREAD

**Issue by Caydo163** [Garulf/HA-Commander#37]
I looked at the place specified on the doc https://developers.home-assistant.io/docs/auth_api/#long-lived-access-token but I can't find and I don't know how websockets work . Could I get some help?

**Comment by Garulf** [comment]
Sorry looks like Home Assistant doesn't provide clear instructions on this. Simply go to your profile by clicking your name on the bottom left. 

Scroll to the bottom of your profile page and click "create token"
