### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by AnthonMS** [Garulf/HA-Commander#38]
Hello, I can see you have been busy creating Flow Launcher plugins. I love them all! Great work!

I am having some issues setting this one up though, and I'm sure it's just because I'm doing something wrong.

I have installed the plugin through PM command and I have given it the correct URL and generated a token and disabled Verify SSL, since I will be accessing over local network always on this PC.

I have disabled Verify SSL, since I didn't think it would work with SSL because I access it over LAN. Though, when I enable Verify SSL and restart flow launcher, then Flow Launcher crashes before it even starts and the Flow command window never opens on shortcut, until I open Flow Launcher settings, disable HA-Commander and restart Flow Launcher again. 

So Flow Launcher crashes completely when I enable Verify SSL.

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File C:\Users\Anthon\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.0\lib\flox\launcher.py, line 44, in run
    results = request_method(*request_parameters) or self._results
  File C:\Users\Anthon\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.0\lib\flox\__init__.py, line 131, in _query
    self.query(query)
  File C:\Users\Anthon\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.0\plugin\main.py, line 53, in query
    states = self.client.states()
  File C:\Users\Anthon\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.0\plugin\homeassistant.py, line 118, in states
    entities.append(self.create_entity(entity))
  File C:\Users\Anthon\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.0\plugin\homeassistant.py, line 143, in create_entity
    return _cls(self, entity)
  File C:\Users\Anthon\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.0.0\plugin\homeassistant.py, line 432, in __init__
    for option in self.attributes[options]:
KeyError: 'options'

```
</p>
</details>

**Comment by Garulf** [comment]
Looks like I'm using an unsafe key lookup for `input_select` entities. I'll have a fix for that in a moment.

https://github.com/Garulf/HA-Commander/blob/f34177514e4525c1ec50cf32727f875041e64d71/plugin/homeassistant.py#L425-L440

**Comment by Garulf** [comment]
Fixed! The update should appear in Flow in 3 hours or so when the manifest is updated.


> Hello, I can see you have been busy creating Flow Launcher plugins. I love them all! Great work!

Thanks! Coming from Apple I had a ton of personal plugins I made for launcher's. After moving to Windows Flow Launcher was a perfect replacement. Glad you're able to enjoy them! HA-Commander is incredibly useful for Home Assistant you'll love it.

> I am having some issues setting this one up though, and I'm sure it's just because I'm doing something wrong.
> 
> I have installed the plugin through PM command and I have given it the correct URL and generated a token and disabled Verify SSL, since I will be accessing over local network always on this PC.
> 
> I have disabled Verify SSL, since I didn't think it would work with SSL because I access it over LAN. Though, when I enable Verify SSL and restart flow launcher, then Flow Launcher crashes before it even starts and the Flow command window never opens on shortcut, until I open Flow Launcher settings, disable HA-Commander and restart Flow Launcher again.
> 
> So Flow Launcher crashes completely when I enable Verify SSL.

The library I use for http requests has some quirks using SSL when packaged in a zip file. This might be the issue?
