### ISSUE TITLE
verify_ssl is ignored

### ISSUE THREAD

**Issue by OptionalM** [Garulf/HA-Commander#43]
The field `verify_ssl` in the settings is ignored.
Hard coding it in `homeassistant.py:113` fixes it for me, but I couldn't figure out the correct way to use the settings value.

**Comment by Garulf** [comment]
I have tested and debugged this myself. The settings is being used and changed.

Do keep in mind Flow Launcher does not update/save its settings until *after* you close the settings window.

Perhaps this is the behavior you're seeing?

**Comment by OptionalM** [comment]
Yes, you are correct. I was quite sure since I'd been trying for quite a while, but not enough it seems.
