### ISSUE TITLE
First install, getting TypeError

### ISSUE THREAD

**Issue by MaximeNagel** [Garulf/HA-Commander#61]
Hi, I have just discovered Flowlauncher and I have try tu use your plugin for HA but it seems that something is wrong.
I'm not even sure if it's correctly login to my HA instance because I don't see anything on the HA Log side

I have set the correct URL + Port put SSL to false and create a long Auth API key : 
![image](https://github.com/Garulf/HA-Commander/assets/6407540/16599190-e5e2-4805-bbdb-6948cd4fec93)

Am I missing something else ? 
<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\mnage\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mnage\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\mnage\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\plugin\main.py", line 53, in query
    states = self.client.states()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mnage\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\plugin\homeassistant.py", line 122, in states
    entities.append(self.create_entity(entity))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mnage\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\plugin\homeassistant.py", line 147, in create_entity
    return _cls(self, entity)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mnage\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\plugin\homeassistant.py", line 455, in __init__
    for option in self.attributes["options"]:
TypeError: 'NoneType' object is not iterable

```
</p>
</details>

Screenshot :
![image](https://github.com/Garulf/HA-Commander/assets/6407540/ec188f7b-2868-4d25-bb72-2f7ea6ba2f70)

**Comment by robertoleonardo** [comment]
same issue here, except mine started happening very suddenly just now after having teh plugin working fine for a year or two.  i've got flow pointed to the embeddable pythonw.exe file.  have tried uninstalling and completely removing the ha-commander plugin  data and reinstalling -- no dice.

**Comment by robertoleonardo** [comment]
I've started getting a similar error after ha-commander working without issue for many months, thoough it seems to be taking issue with different lines of code.  its hard to say what exactly caused it -- i initially thought it was when i udpated to home assistant 2024.6.1 that this error occurred, but after rolling back to a backup and then updating to 2024.6.1 -- it continued to work for a period.  but then overnight, with nothing else changed as far as i can tell, the issue started again.  it's happening on both of my machines -- a w10 laptop and a w11 pc.

```
Traceback (most recent call last):
  File "C:\Users\RJL\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RJL\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\lib\flox\__init__.py", line 134, in _context_menu
    self.context_menu(data)
  File "C:\Users\RJL\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-5.1.1\plugin\main.py", line 153, in context_menu
    entity = data[0]
             ~~~~^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by Garulf** [comment]
Looks like an easy enough fix. I'll try and patch this when i have the time.

**Comment by robertoleonardo** [comment]
I have no idea if this is a proper fix, so i won't make it a pull request, but wanted to flag here just in case it's helpful for anyone else pending a real fix from @Garulf.

i was able to brute force my way into getting it working again with a small tweak to \plugin\homeassistant.py -- line 257, added "or []" to the end, so that it reads in full:

        `for effect in self.attributes.get("effect_list", []) or []:`

it remains to be seen if that is just a bandaid and some other issue will surface because of it. but for now, it's working again for me.

**Comment by Garulf** [comment]
@robertoleonardo Yes this is actually the proper fix. I should not have assumed this key would always be present.

**Comment by Garulf** [comment]
> I have no idea if this is a proper fix, so i won't make it a pull request, but wanted to flag here just in case it's helpful for anyone else pending a real fix from @Garulf.
> 
> i was able to brute force my way into getting it working again with a small tweak to \plugin\homeassistant.py -- line 257, added "or []" to the end, so that it reads in full:
> 
> ```
>     `for effect in self.attributes.get("effect_list", []) or []:`
> ```
> 
> it remains to be seen if that is just a bandaid and some other issue will surface because of it. but for now, it's working again for me.

I was looking at the code to make a proper fix and realized that the `.get` method should have caught an empty dict. What does your log say before you patched it?

**Comment by robertoleonardo** [comment]
interesting. it didn't seem to catch it here -- that seemed to be what was causing the "None type. object not iterable" error

**Comment by Wraiyth** [comment]
I know this issue is closed, but I encountered a similar issue.
FYI I had to make a similar change for this issue on L455

`for option in self.attributes.get("options", []) or []:`
